import { Prisma } from "@/lib/generated/prisma/client";
import type { AlertFacts } from "@/lib/alerts/catalog";
import type { PolicyValues } from "@/lib/policies/registry";
import type { BreakdownRow } from "@/lib/finance/breakdown";

/**
 * §3.4's Key Insights — the three plain-English sentences at the foot of the Executive
 * dashboard.
 *
 * In lib/, not in a component, and that placement is the point. These sentences state
 * financial conclusions, and a conclusion assembled inside a JSX file is a conclusion
 * nobody can test. Here they are a pure function over the same facts the alert catalogue
 * reads, so `verify:dashboard` can assert that a district under its reserve target is told
 * so — and so the wording lives beside the alerts it must not contradict.
 *
 * Not generated by a model, either. A sentence on a superintendent's dashboard has to be
 * reproducible and auditable; the district's own numbers and thresholds decide it.
 *
 * An insight only appears when its underlying fact is non-null. Three is a maximum, not a
 * quota — a district in good order gets fewer, and that is the correct output.
 */

export interface Insight {
  id: string;
  direction: "up" | "down" | "flag";
  text: string;
}

const pct = (v: Prisma.Decimal) => `${v.abs().toFixed(2)}%`;

export function buildInsights(args: {
  facts: AlertFacts;
  policy: PolicyValues;
  /** Top revenue sources by pace variance, for naming the reason. */
  revenueMovers?: BreakdownRow[];
  expenditureMovers?: BreakdownRow[];
}): Insight[] {
  const { facts, policy } = args;
  const out: Insight[] = [];

  // ---- revenue against pace ----
  const rv = facts.revenueVariancePercent;
  if (rv !== null && !rv.isZero()) {
    const ahead = rv.isPositive();
    const leaders = (args.revenueMovers ?? [])
      .filter((r) => (ahead ? r.pace.amount.isPositive() : r.pace.amount.isNegative()))
      .slice(0, 2)
      .map((r) => r.name);

    const because = leaders.length
      ? `, led by ${leaders.join(" and ")}`
      : "";

    out.push({
      id: "revenue-pace",
      direction: ahead ? "up" : "down",
      text: `Revenues are ${ahead ? "ahead of" : "behind"} budget by ${pct(rv)} for the year to date${because}.`,
    });
  }

  // ---- spending against budget ----
  const util = facts.utilizationPercent;
  if (util !== null) {
    const warning = Number(policy.expenditure.utilizationWarning);
    const over = util.greaterThanOrEqualTo(warning);
    const leaders = (args.expenditureMovers ?? [])
      .filter((r) => r.pace.amount.isPositive())
      .slice(0, 2)
      .map((r) => r.name);

    out.push({
      id: "expenditure-utilisation",
      direction: over ? "down" : "up",
      text: over
        ? `${pct(util)} of the expenditure budget is committed, at or past your ${warning}% warning threshold${leaders.length ? `, driven by ${leaders.join(" and ")}` : ""}.`
        : `${pct(util)} of the expenditure budget is committed, within your ${warning}% warning threshold.`,
    });
  }

  // ---- the reserve, which is the figure a board asks about ----
  const reserve = facts.reservePercent;
  if (reserve !== null) {
    const target = Number(policy.fundBalance.target);
    const below = reserve.lessThan(target);
    out.push({
      id: "reserve",
      direction: below ? "flag" : "up",
      text: below
        ? `Unassigned fund balance is ${pct(reserve)}, below the ${target.toFixed(2)}% policy target. Continued monitoring is recommended.`
        : `Unassigned fund balance is ${pct(reserve)}, at or above the ${target.toFixed(2)}% policy target.`,
    });
  }

  // ---- cash, only when it is the thing worth saying ----
  const days = facts.daysCashOnHand;
  if (out.length < 3 && days !== null) {
    const warning = Number(policy.cash.daysCashWarning);
    if (days.lessThan(warning)) {
      out.push({
        id: "cash",
        direction: "flag",
        text: `Days of operating cash stands at ${days.toFixed(0)}, below your ${warning}-day policy.`,
      });
    }
  }

  return out.slice(0, 3);
}
