import { Prisma } from "@/lib/generated/prisma/client";
import type { AlertFacts } from "@/lib/alerts/catalog";
import type { PolicyValues } from "@/lib/policies/registry";
import type { BreakdownRow } from "@/lib/finance/breakdown";
import { compactMoney, sharePercent } from "@/lib/dashboard/format";

/**
 * §3.4's Key Insights — the plain-English sentences at the foot of the Executive dashboard.
 *
 * In lib/, not in a component, and that placement is the point. These sentences state
 * financial conclusions, and a conclusion assembled inside a JSX file is a conclusion
 * nobody can test. Here they are a pure function over the same facts the alert catalogue
 * reads, so `verify:dashboard` can assert that a district under its reserve target is told
 * so — and so the wording lives beside the alerts it must not contradict.
 *
 * Not generated by a model, either. A sentence on a superintendent's dashboard has to be
 * reproducible and auditable; the district's own numbers and thresholds decide it.
 *
 * M4 added two things the client asked for. Each insight now carries a `detail` — the
 * second, lighter line in their mockup, which says what the headline MEANS rather than
 * restating it — and an `href`, because "allow insights to become clickable" only works if
 * the insight itself knows which dashboard answers it. Guessing that in the component would
 * put the routing table two files away from the sentence that needs it.
 *
 * An insight only appears when its underlying fact is non-null. Three is a maximum, not a
 * quota — a district in good order gets fewer, and that is the correct output.
 */

export interface Insight {
  id: string;
  direction: "up" | "down" | "flag";
  /** The headline. States the figure. */
  text: string;
  /** The consequence. States what to do about it, or that nothing needs doing. */
  detail?: string;
  /** The dashboard that answers the question this insight raises. */
  href?: string;
}

const pct = (v: Prisma.Decimal) => `${v.abs().toFixed(2)}%`;

export function buildInsights(args: {
  facts: AlertFacts;
  policy: PolicyValues;
  /** Top revenue sources by pace variance, for naming the reason. */
  revenueMovers?: BreakdownRow[];
  expenditureMovers?: BreakdownRow[];
}): Insight[] {
  const { facts, policy } = args;
  const out: Insight[] = [];

  // ---- revenue against pace ----
  const rv = facts.revenueVariancePercent;
  if (rv !== null && !rv.isZero()) {
    const ahead = rv.isPositive();
    const leaders = (args.revenueMovers ?? [])
      .filter((r) => (ahead ? r.pace.amount.isPositive() : r.pace.amount.isNegative()))
      .slice(0, 2)
      .map((r) => r.name);

    out.push({
      id: "revenue-pace",
      direction: ahead ? "up" : "down",
      text: `Revenues are ${pct(rv)} ${ahead ? "above" : "below"} budget year to date.`,
      detail: leaders.length
        ? `Led by ${leaders.join(" and ")}. Collections are trending ${ahead ? "above" : "below"} expected levels.`
        : `Collections are trending ${ahead ? "above" : "below"} expected levels.`,
      href: "/revenues",
    });
  }

  // ---- available budget, which is the figure a business office plans against ----
  const available = facts.availableBudget;
  const share = sharePercent(available, facts.expenditureBudget);
  if (!facts.expenditureBudget.isZero()) {
    const over = available.isNegative();
    out.push({
      id: "available-budget",
      direction: over ? "down" : "up",
      text: over
        ? `Budget is overcommitted by ${compactMoney(available.abs())}.`
        : `Available budget is ${compactMoney(available)}${share === null ? "" : ` (${share.toFixed(0)}% of full-year budget)`}.`,
      detail: over
        ? "Spending plus encumbrances exceeds the adopted budget."
        : "Sufficient remaining budget for planned activities.",
      href: "/expenditures",
    });
  }

  // ---- spending against budget ----
  const util = facts.utilizationPercent;
  if (util !== null) {
    const warning = Number(policy.expenditure.utilizationWarning);
    const over = util.greaterThanOrEqualTo(warning);
    const leaders = (args.expenditureMovers ?? [])
      .filter((r) => r.pace.amount.isPositive())
      .slice(0, 2)
      .map((r) => r.name);

    out.push({
      id: "expenditure-utilisation",
      direction: over ? "down" : "up",
      text: `${pct(util)} of the expenditure budget is committed.`,
      detail: over
        ? `At or past your ${warning}% warning threshold${leaders.length ? `, driven by ${leaders.join(" and ")}` : ""}.`
        : `Within your ${warning}% warning threshold.`,
      href: "/expenditures",
    });
  }

  // ---- the reserve, which is the figure a board asks about ----
  const reserve = facts.reservePercent;
  if (reserve !== null) {
    const target = Number(policy.fundBalance.target);
    const below = reserve.lessThan(target);
    out.push({
      id: "reserve",
      direction: below ? "flag" : "up",
      text: below
        ? "Unassigned fund balance is below policy target."
        : `Unassigned fund balance is ${pct(reserve)}, at or above policy target.`,
      detail: below
        ? `${pct(reserve)} against a ${target.toFixed(2)}% target. Action needed to rebuild reserves.`
        : `${pct(reserve)} against a ${target.toFixed(2)}% target.`,
      href: "/fund-balance",
    });
  }

  // ---- cash, only when it is the thing worth saying ----
  const days = facts.daysCashOnHand;
  if (days !== null) {
    const warning = Number(policy.cash.daysCashWarning);
    if (days.lessThan(warning)) {
      out.push({
        id: "cash",
        direction: "flag",
        text: `Days of operating cash stands at ${days.toFixed(0)}.`,
        detail: `Below your ${warning}-day policy minimum.`,
        href: "/cash",
      });
    }
  }

  // Worst news first: a superintendent reading three of these should read the flags before
  // the reassurances, whatever order the facts happened to be computed in.
  const rank = { flag: 0, down: 1, up: 2 } as const;
  return [...out].sort((a, b) => rank[a.direction] - rank[b.direction]).slice(0, 3);
}

/**
 * The one-sentence narrative under a trend chart — §3.2b's Fund Balance key insight and
 * §7.2's Cash key insight.
 *
 * Separate from `buildInsights` because it answers a different question. The Key Insights
 * card ranks what matters across the whole district; this states what the chart directly
 * above it just showed, which is a caption rather than a conclusion.
 */
export function trendNarrative(args: {
  subject: string;
  current: Prisma.Decimal | null;
  previous: Prisma.Decimal | null;
  periodLabel: string;
  previousLabel: string;
}): string | null {
  const { current, previous } = args;
  if (current === null || previous === null || previous.isZero()) return null;

  const change = current.minus(previous);
  const percentChange = change.dividedBy(previous.abs()).times(100);
  const direction = change.isNegative() ? "decreased" : "increased";

  return `${args.subject} ${direction} ${compactMoney(change.abs())} (${percentChange.abs().toFixed(2)}%) from ${args.previousLabel} to ${args.periodLabel}, ending at ${compactMoney(current)}.`;
}
