-- Unify the Grants and Capital Projects masters into a single Project master (MVP).
--
-- The Grant and CapitalProject tables are kept (dormant, for the V2 modules), but the
-- finance pipeline no longer references them: the single "Project / Grant" column on the
-- detail imports now resolves to one Project. So the grantId + capitalProjectId columns on
-- the three periodic tables collapse into a single projectId -> Project.
--
-- The dropped tag columns are regenerated by re-running the sample import; no other data
-- is touched.

-- CreateTable
CREATE TABLE "Project" (
    "id" TEXT NOT NULL,
    "districtId" TEXT NOT NULL,
    "projectNumber" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "active" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Project_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "Project_districtId_idx" ON "Project"("districtId");

-- CreateIndex
CREATE UNIQUE INDEX "Project_districtId_projectNumber_key" ON "Project"("districtId", "projectNumber");

-- DropForeignKey
ALTER TABLE "BudgetLine" DROP CONSTRAINT "BudgetLine_capitalProjectId_fkey";

-- DropForeignKey
ALTER TABLE "BudgetLine" DROP CONSTRAINT "BudgetLine_grantId_fkey";

-- DropForeignKey
ALTER TABLE "RevenueActual" DROP CONSTRAINT "RevenueActual_grantId_fkey";

-- DropForeignKey
ALTER TABLE "RevenueActual" DROP CONSTRAINT "RevenueActual_capitalProjectId_fkey";

-- DropForeignKey
ALTER TABLE "ExpenditureActual" DROP CONSTRAINT "ExpenditureActual_grantId_fkey";

-- DropForeignKey
ALTER TABLE "ExpenditureActual" DROP CONSTRAINT "ExpenditureActual_capitalProjectId_fkey";

-- AlterTable
ALTER TABLE "BudgetLine" DROP COLUMN "capitalProjectId",
DROP COLUMN "grantId",
ADD COLUMN     "projectId" TEXT;

-- AlterTable
ALTER TABLE "RevenueActual" DROP COLUMN "grantId",
DROP COLUMN "capitalProjectId",
ADD COLUMN     "projectId" TEXT;

-- AlterTable
ALTER TABLE "ExpenditureActual" DROP COLUMN "grantId",
DROP COLUMN "capitalProjectId",
ADD COLUMN     "projectId" TEXT;

-- AddForeignKey
ALTER TABLE "Project" ADD CONSTRAINT "Project_districtId_fkey" FOREIGN KEY ("districtId") REFERENCES "District"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "BudgetLine" ADD CONSTRAINT "BudgetLine_projectId_fkey" FOREIGN KEY ("projectId") REFERENCES "Project"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "RevenueActual" ADD CONSTRAINT "RevenueActual_projectId_fkey" FOREIGN KEY ("projectId") REFERENCES "Project"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ExpenditureActual" ADD CONSTRAINT "ExpenditureActual_projectId_fkey" FOREIGN KEY ("projectId") REFERENCES "Project"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
